var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__f6d4e657._.js")
R.c("server/chunks/ssr/[root-of-the-server]__904fe76f._.js")
R.c("server/chunks/ssr/f61bf_next_dist_a34e8c1a._.js")
R.c("server/chunks/ssr/src_app_ca777385._.js")
R.c("server/chunks/ssr/[root-of-the-server]__11fa4345._.js")
R.c("server/chunks/ssr/f61bf_next_dist_client_components_2830cc5a._.js")
R.c("server/chunks/ssr/f61bf_next_dist_client_components_builtin_forbidden_569b9aba.js")
R.c("server/chunks/ssr/f61bf_next_dist_client_components_builtin_unauthorized_c9640ecd.js")
R.c("server/chunks/ssr/f61bf_next_dist_client_components_builtin_global-error_be95489f.js")
R.c("server/chunks/ssr/[root-of-the-server]__f940c5dd._.js")
R.c("server/chunks/ssr/_e48fb8e5._.js")
R.c("server/chunks/ssr/_67e5443f._.js")
R.m(49901)
R.m(17646)
module.exports=R.m(17646).exports
