var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__d0c325b4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__904fe76f._.js")
R.c("server/chunks/ssr/f61bf_next_dist_a34e8c1a._.js")
R.c("server/chunks/ssr/src_app_ca777385._.js")
R.c("server/chunks/ssr/[root-of-the-server]__11fa4345._.js")
R.c("server/chunks/ssr/f61bf_next_dist_client_components_2830cc5a._.js")
R.c("server/chunks/ssr/f61bf_next_dist_client_components_builtin_forbidden_569b9aba.js")
R.c("server/chunks/ssr/[root-of-the-server]__cd42a090._.js")
R.c("server/chunks/ssr/_e48fb8e5._.js")
R.c("server/chunks/ssr/f61bf_next_dist_ecfef73c._.js")
R.m(57665)
R.m(63499)
module.exports=R.m(63499).exports
